_BASE_: "Base-RCNN-VoVNet-FPN.yaml"
MODEL:
  #WEIGHTS: "https://www.dropbox.com/s/rptgw6stppbiw1u/vovnet19_ese_detectron2.pth?dl=1"
  WEIGHTS: "/home/masato/vovnet19_ese_detectron2.pth"
  MASK_ON: False
  VOVNET:
    CONV_BODY : "V-19-eSE"
  FPN:
    OUT_CHANNELS: 128
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
#SOLVER:
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.04
  STEPS: (30000, 40000)
  MAX_ITER: 45000
OUTPUT_DIR: "checkpoints/CRCN-V2-FPNLite-19-1x"
